package jm.section42;

public enum ExceptionTypes {
    CONNECTION_EXCEPTION,
    MOVEMENT_EXCEPTION,
    CLOSING_EXCEPTION,
    CONNECTION_RANDOM_EXCEPTION,
    MOVEMENT_RANDOM_EXCEPTION,
    CLOSING_RANDOM_EXCEPTION,
    NONE
}
